name: Test

on:
  workflow_call:
    inputs:
      min-coverage:
        type: string
        default: '90'
      upload-coverage:
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-python-env # Chama a sua action local
        with:
          make-target: 'setup-tests'

      - name: Run tests with coverage
        run: make test MIN_COVERAGE=${{ inputs.min-coverage }}
        env:
          PYTHONPATH: .

      - name: Upload coverage reports
        if: ${{ inputs.upload-coverage }}
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
