name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-python-env # Chama a sua action local
        with:
          install-extras: 'dev'

      - name: Lint with Ruff
        run: ruff check src tests

      - name: Format check with Black
        run: black --check src tests

      - name: Type checking with Mypy
        run: mypy src || true
